repos:
  # fuzzing-sample-product-poc:
  #   owner: hypothesis-imperial
  #   name: fuzzing-sample-product-poc
  #   git_url: https://github.com/hypothesis-imperial/fuzzing-sample-product-poc.git
  #   branch: master # optional; Default master
  attrs:
    owner: hypothesis-imperial
    name: attrs
    git_url: https://github.com/hypothesis-imperial/attrs.git
    branch: master # optional; Default master
    dependencies:
      all: ".[tests]"
