repos:
  fuzzing-sample-product-poc:
    owner: hypothesis-imperial
    name: fuzzing-sample-product-poc
    git_url: https://github.com/hypothesis-imperial/fuzzing-sample-product-poc.git
    branch: master # optional; Default master
    project_root: project_root
  attrs:
    owner: hypothesis-imperial
    name: attrs
    git_url: git@github.com:hypothesis-imperial/attrs.git
    dependencies:
      all: ".[tests]"
      our_hypothesis: "requirements.txt"
  cryptogtraphy:
    owner: hypothesis-imperial
    name: cryptography
    git_url: git@github.com:hypothesis-imperial/cryptography.git
    dependencies:
      cryptography: "."
      dev-req: "dev-requirements.txt"
