version: 2
jobs:
  deploy:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: Copy over deploy script
          command: scp -o 'StrictHostKeyChecking=no' deploy_scripts/update-fuzzer ubuntu@ec2-18-130-116-158.eu-west-2.compute.amazonaws.com:/fuzzer/
      - run:
          name: SSH and run Deploy Script
          command: ssh -o "StrictHostKeyChecking=no" -v ubuntu@ec2-18-130-116-158.eu-west-2.compute.amazonaws.com "update-fuzzer"

workflows:
  version: 2
  deploy_branch:
    jobs:
      - deploy
