#!/bin/bash

set -e

cd /fuzzer/fuzzing-server-poc
git reset --hard origin/master
git pull
rm -rf venv
virtualenv  -p python3 venv
source venv/bin/activate
pip install -r requirements.txt
pip install virtualenv
pip install "git+git://github.com/hypothesis-imperial/hypothesis.git#subdirectory=hypothesis-python"

# Kill old tmux server
tmux kill-server || echo "No previous server"

sleep 3
tmux new-session -d -s fuzzer
tmux send-keys "source venv/bin/activate && sudo env \"PATH=\$PATH\" python3 app.py" C-m
